/* ============================================================
   RIVER TIERS — the file to edit when you disagree with a ranking.

   Every river gets a quality class:

     gold  the destination water — recognised blue-ribbon fisheries
     "1"   very good, worth a drive
     "2"   good, worth it if you're already nearby
     "3"   the rest. Hidden by default; the "All rivers" chip shows them.

   A river that is not listed here is Class 3. That is the safe default:
   a new river never clutters the map until someone decides it deserves to.

   The scale is RELATIVE TO ITS REGION, on purpose. The West has far more
   blue-ribbon water than the Midwest, so it has more Gold; a Driftless
   creek that is Class 1 is a great stream *for the Driftless*, not a claim
   that it matches the Madison. These are researched starting points, not
   official ratings — overrule them from experience. The Driftless list in
   particular is a draft.

   `season` (all optional) shifts the class by the calendar month:
     best:[[a,b],...]   in-window → one class better (Class 3 → 2, 2 → 1, 1 → Gold)
     poor:[[a,b],...]   in-window → one class worse (Gold → 1 … 2 → 3)
     closed:[[a,b],...] in-window → the water is shut; treated as Class 3
   Months are 1–12 and a window may wrap the new year ([11,4] = Nov–Apr).
   `why` is the one line the sheet shows. It states the reason, never a
   made-up number — this is a window table, not a forecast. A river with
   live flow data still shows its real CFS status beside the tier.
   ============================================================ */
const TIER_ORDER = ["3","2","1","gold"];          // worst → best
const TIERS = {
  /* ---- Jackson Hole / Snake ---- */
  snake:        {t:"gold", season:{best:[[8,10]], poor:[[4,6]],
                  why:"Runoff keeps the Snake high and off-colour through June; it clears and fishes best Aug–Oct."}},
  southfork:    {t:"gold", season:{best:[[4,5],[9,11]],
                  why:"Dam-controlled, so it stays clear when the freestones blow out in spring; big fall browns and BWOs Sept–Nov."}},
  grosventre:   {t:"1", season:{best:[[7,10]], poor:[[4,6]], why:"Snowmelt-muddy until early July."}},
  hoback:       {t:"2", season:{best:[[7,9]],  poor:[[4,6]], why:"Snowmelt-muddy until early July."}},
  buffalofork:  {t:"2", season:{best:[[7,9]],  poor:[[4,6]], why:"Snowmelt-muddy until early July."}},
  flatcreek:    {t:"2"},
  salt:         {t:"2", season:{best:[[7,10]], poor:[[4,6]], why:"Runoff through June."}},
  greys:        {t:"2", season:{best:[[7,10]], poor:[[4,6]], why:"Runoff through June."}},
  snakeflagg:   {t:"2", season:{best:[[7,9]], poor:[[4,6]], why:"Runoff through June."}},

  /* ---- Eastern Idaho, Henry's Fork country ---- */
  henrysfork:   {t:"gold", season:{best:[[6,10]], why:"Salmonflies and green drakes in June; fishes well all summer and fall."}},
  fallriver:    {t:"1", season:{best:[[6,10]]}},
  silvercreek:  {t:"gold", season:{best:[[5,6],[9,10]], why:"Spring-creek hatches peak late spring and early fall."}},
  bigwood:      {t:"1", season:{best:[[6,10]], poor:[[4,5]], why:"Runoff in May."}},
  teton:        {t:"gold", season:{best:[[7,10]], poor:[[4,6]],
                  why:"Runoff muddies the valley in spring; it clears later than the South Fork and fishes best July–Oct."}},
  boise:        {t:"1"},
  sfboise:      {t:"1", season:{best:[[4,5],[9,11]]}},

  /* ---- Central Idaho ---- */
  salmon:       {t:"1", season:{best:[[7,9]], poor:[[4,6]], why:"High, cold and off-colour through June."}},
  mfsalmon:     {t:"1", season:{best:[[7,9]], poor:[[4,6]], why:"Wilderness cutthroat water; fishable after runoff."}},
  lemhi:        {t:"2"},
  selway:       {t:"1", season:{best:[[7,8]], poor:[[4,6]], why:"Runoff through June."}},
  lochsa:       {t:"2", season:{best:[[7,9]], poor:[[4,6]]}},
  clearwater:   {t:"2"},
  nfclearwater: {t:"2", season:{best:[[7,9]], poor:[[4,6]]}},
  stjoe:        {t:"1", season:{best:[[7,9]], poor:[[4,6]], why:"Runoff through June; dry-fly cutthroat July–Sept."}},
  cda:          {t:"2"},
  kootenai:     {t:"2"},
  snakeid:      {t:"2"},
  hellscanyon:  {t:"2"},

  /* ---- Wyoming ---- */
  nplattereef:  {t:"gold"},
  nplatteupper: {t:"1", season:{poor:[[5,6]], why:"Runoff in May–June."}},
  green:        {t:"1", season:{best:[[7,9]], poor:[[5,6]], why:"Runoff in May–June."}},
  newfork:      {t:"2", season:{poor:[[5,6]]}},
  nfshoshone:   {t:"2", season:{best:[[7,9]], poor:[[5,6]]}},
  shoshone:     {t:"2"},
  clarksfork:   {t:"2", season:{best:[[8,10]], poor:[[5,7]]}},
  encampmentwy: {t:"2"},

  /* ---- Yellowstone (the 166 unnamed-by-anyone creeks stay Class 3) ---- */
  madisonriver:     {t:"gold", season:{best:[[5,6],[9,10]], closed:[[11,4]],
                      why:"Opens May 1; fly-fishing only. Best in early summer and the fall brown run."}},
  fireholeriver:    {t:"gold", season:{best:[[5,6],[9,10]], poor:[[7,8]], closed:[[11,4]],
                      why:"Opens May 1. Thermal water runs too warm in July–August; best early summer and fall."}},
  gibbonriver:      {t:"1",    season:{best:[[5,6],[9,10]], closed:[[11,4]], why:"Opens May 1."}},
  yellowstoneriver: {t:"gold", season:{best:[[7,9]], closed:[[11,6]],
                      why:"Yellowstone below the lake opens July 1."}},
  lamarriver:       {t:"gold", season:{best:[[7,9]], poor:[[5,6]], closed:[[11,4]],
                      why:"Runoff-high until early July; season opens Memorial Day weekend."}},
  sloughcreek:      {t:"gold", season:{best:[[7,9]], poor:[[5,6]], closed:[[11,4]],
                      why:"Runoff-high until early July; season opens Memorial Day weekend."}},
  sodabuttecreek:   {t:"1",    season:{best:[[7,9]], poor:[[5,6]], closed:[[11,4]]}},
  gardnerriver:     {t:"2",    season:{best:[[8,10]], poor:[[4,6]], why:"Runoff through June."}},
  lewisriver:       {t:"2",    season:{best:[[9,10]], closed:[[11,6]], why:"Fall brown trout run out of Lewis Lake."}},
  bechlerriver:     {t:"2",    season:{best:[[7,9]], closed:[[11,5]]}},
  gallatinyell:     {t:"2",    season:{best:[[7,9]], closed:[[11,5]]}},
  specimencreek:    {t:"2",    season:{best:[[7,9]], closed:[[11,5]]}},
  hellroaringcreek: {t:"2",    season:{best:[[7,9]], closed:[[11,5]]}},
  pelicancreek:     {t:"2",    season:{closed:[[11,7]], why:"Lake tributary: opens July 15."}},

  /* ---- Grand Teton — most park streams closed Dec 1–Jul 31 ---- */
  pacificcreek: {t:"2", season:{best:[[8,10]], poor:[[4,6]], why:"Runoff through June (open year-round under park exemption)."}},
  spreadcreek:  {t:"2", season:{best:[[8,9]], why:"The park reach is closed December 1 – July 31; the rest of the creek is open under Wyoming rules."}},

  /* ---- Teton Valley & Swan Valley: tributaries close June 1–30 ---- */
  tv_bitchcreek:      {t:"2", season:{best:[[8,10]], poor:[[4,5]], closed:[[6,6]]}},
  tv_darbycreek:      {t:"2", season:{best:[[7,10]], poor:[[4,5]], closed:[[6,6]]}},
  sv_palisadescreek:  {t:"2", season:{best:[[7,10]], poor:[[4,5]], closed:[[6,6]]}},
  sv_raineycreek:     {t:"2", season:{best:[[7,10]], poor:[[4,5]], closed:[[6,6]]}},
  sv_bigelkcreek:     {t:"2", season:{best:[[7,10]], poor:[[4,5]], closed:[[6,6]]}},

  /* ---- Central Iowa (warmwater float rivers) ---- */
  desmoines:    {t:"2"},
  // Pilot Central water (the Des Moines area): visible by default alongside the Des Moines, not hidden as Class 3.
  raccoon:      {t:"2"},
  beavercreek:  {t:"2"},

  /* ---- Driftless — DRAFT: please review, this is the region you know best ---- */
  kinnickinnic: {t:"gold"},
  timbercoulee: {t:"gold"},
  // Iowa
  waterloocreek:{t:"1"}, bloodyrun:{t:"1"}, yellowriver:{t:"1"}, frenchcreek:{t:"1"},
  paintcreek:{t:"1"}, springbranchia:{t:"1"},
  upperiowa:{t:"2"}, troutrunia:{t:"2"}, coldwaterIA:{t:"2"}, canoecreek:{t:"2"},
  iaCaseySprings:{t:"2"}, iaEnsignHollowCreek:{t:"2"}, iaFalconSpringBranch:{t:"2"},
  iaPineSpringCreek:{t:"2"}, iaSouthPineCreek:{t:"2"}, iaWestFrenchCreek:{t:"2"},
  // Minnesota
  whitewater:{t:"1"},
  rootriver:{t:"2"}, sfroot:{t:"2"}, mfwhitewater:{t:"2"}, garvinbrook:{t:"2"},
  troutrunmn:{t:"2"}, beavercreekmn:{t:"2"}, duschee:{t:"2"}, haycreek:{t:"2"},
  crookedcreekmn:{t:"2"}, vermillionmn:{t:"2"},
  // Wisconsin
  cooncreek:{t:"1"}, blackearth:{t:"1"}, rushriverwi:{t:"1"}, trimbelle:{t:"1"},
  kickapoo:{t:"2"}, wforkkickapoo:{t:"2"}, tainter:{t:"2"}, badaxe:{t:"2"},
  rushcreekwi:{t:"2"}, mountvernon:{t:"2"}, castlerock:{t:"2"}, biggreen:{t:"2"},
  grantriver:{t:"2"}, ebpecatonica:{t:"2"}, silvercreekwi:{t:"2"}, stillwell:{t:"2"},

  /* ---- North Shore — steelhead run in spring and fall ---- */
  boisbrulewi:    {t:"gold", season:{best:[[4,5],[9,10]], why:"Steelhead run in spring and fall."}},
  kniferiverns:   {t:"1", season:{best:[[4,5],[9,10]], why:"Steelhead run in spring and fall."}},
  gooseberryriver:{t:"1", season:{best:[[4,5],[9,10]], why:"Steelhead run in spring and fall."}},
  baptismriver:   {t:"1", season:{best:[[4,5],[9,10]], why:"Steelhead run in spring and fall."}},
  splitrockriver: {t:"1", season:{best:[[4,5],[9,10]], why:"Steelhead run in spring and fall."}},
  temperanceriver:{t:"1", season:{best:[[4,5],[9,10]], why:"Steelhead run in spring and fall."}},
  cascaderiver:   {t:"2", season:{best:[[4,5],[9,10]]}},
  lesterriver:    {t:"2", season:{best:[[4,5],[9,10]]}},
  frenchriverns:  {t:"2", season:{best:[[4,5],[9,10]]}},
  suckerriver:    {t:"2", season:{best:[[4,5],[9,10]]}},
  stewartriver:   {t:"2", season:{best:[[4,5],[9,10]]}},
  deviltrackriver:{t:"2", season:{best:[[4,5],[9,10]]}},
  brulerivermn:   {t:"2", season:{best:[[4,5],[9,10]]}},
  pigeonriver:    {t:"2"},
  stlouisriver:   {t:"2"},

  /* ---- Door Peninsula ---- */
  hibbardscr:   {t:"2"},
  logancr:      {t:"2"},

  /* ---- East-central MN / St. Croix & Northwoods (warmwater; frozen in winter) ---- */
  stcroix:        {t:"1", season:{best:[[6,9]], poor:[[12,3]], why:"Smallmouth season; ice-bound in winter."}},
  namekagonriver: {t:"1", season:{best:[[6,9]], poor:[[12,3]], why:"Smallmouth and trout; ice-bound in winter."}},
  crowwing:       {t:"1", season:{best:[[6,9]], poor:[[12,3]]}},
  rumriver:       {t:"2", season:{poor:[[12,3]]}},
  kettleriver:    {t:"2", season:{poor:[[12,3]]}},
  cannonriver:    {t:"2", season:{poor:[[12,3]]}},
  mississippiTC:  {t:"2", season:{poor:[[12,3]]}},
  straightmn:     {t:"2"},
  prairiewi:      {t:"2"},
  chippewawi:     {t:"2", season:{poor:[[12,3]]}},
  flambeau:       {t:"2", season:{poor:[[12,3]]}},
  sfflambeau:     {t:"2", season:{poor:[[12,3]]}},
  wisconsinriver: {t:"2", season:{poor:[[12,3]]}},
  wolfriverwi:    {t:"2", season:{poor:[[12,3]]}},



/* >>> western national parks (generated by parks/apply.py — re-run, don't hand-edit) */
  /* ---- Western national parks — drafts relative to each park; overrule from experience ---- */
  hohriver:         {t:"gold"},
  sfhoh:            {t:"2"},
  queets:           {t:"1", season:{closed:[[10,11]], why:"Closed October 1 – November 30."}},
  salmonolym:       {t:"2"},
  quinault:         {t:"2"},
  nfquinault:       {t:"2"},
  bogachiel:        {t:"1"},
  solduc:           {t:"1"},
  nfsolduc:         {t:"3"},
  sfcalawah:        {t:"3"},
  elwha:            {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  dosewallips:      {t:"2"},
  duckabush:        {t:"2"},
  graywolf:         {t:"2"},
  nfskokomish:      {t:"2"},
  ozette:           {t:"3"},
  ohanapecosh:      {t:"1", season:{closed:[[11,5]], why:"Open the first Saturday in June until October 31."}},
  whiteriverwa:     {t:"2", season:{closed:[[9,5]], why:"Open the first Saturday in June until Labor Day."}},
  wfwhite:          {t:"3", season:{closed:[[9,5]], why:"Open the first Saturday in June until Labor Day."}},
  huckleberry:      {t:"3", season:{closed:[[9,5]], why:"Open the first Saturday in June until Labor Day."}},
  carbon:           {t:"2", season:{closed:[[9,5]], why:"Open the first Saturday in June until Labor Day."}},
  mowich:           {t:"3", season:{closed:[[9,5]], why:"Open the first Saturday in June until Labor Day."}},
  puyallup:         {t:"3", season:{closed:[[11,5]], why:"Open the first Saturday in June until October 31."}},
  nisqually:        {t:"2", season:{closed:[[11,5]], why:"Open the first Saturday in June until October 31."}},
  cowlitzmora:      {t:"3", season:{closed:[[11,5]], why:"Open the first Saturday in June until October 31."}},
  stehekin:         {t:"gold"},
  skagitnoca:       {t:"1"},
  bigbeaver:        {t:"2"},
  littlebeaver:     {t:"3"},
  thunder:          {t:"2"},
  chilliwack:       {t:"2"},
  bakerriver:       {t:"2"},
  bridgecreeknoca:  {t:"3"},
  ruby:             {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  cascadenoca:      {t:"2"},
  anniecreek:       {t:"2"},
  suncreek:         {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  nfflathead:       {t:"gold", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  mfflathead:       {t:"1", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  mcdonaldcreek:    {t:"1", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  stmaryriver:      {t:"2", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  bellyriver:       {t:"2", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  watertonriver:    {t:"2", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  twomedicine:      {t:"2", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  cutbank:          {t:"2", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  swiftcurrent:     {t:"2", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  kintla:           {t:"3", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  bowmancreek:      {t:"3", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  loggingcreek:     {t:"3", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  quartzcreek:      {t:"3", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  redeagle:         {t:"3", season:{closed:[[12,4]], why:"Park streams open the third Saturday in May through November 30."}},
  olecreek:         {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  parkcreekglac:    {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  coalcreekglac:    {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  nyackcreek:       {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  kennedycreek:     {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  bouldercreekglac: {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  otatsocreek:      {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  leecreek:         {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  muircreek:        {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  fishcreekglac:    {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  nfbelly:          {t:"3", season:{closed:[[1,12]], why:"Closed to fishing."}},
  smithriver:       {t:"gold"},
  redwoodcreek:     {t:"1"},
  prairiecreek:     {t:"3"},
  lostmancreek:     {t:"3"},
  littlelostman:    {t:"3"},
  millcreekredw:    {t:"3"},
  bondcreek:        {t:"3"},
  hatcreek:         {t:"2"},
  kingscreeklavo:   {t:"2"},
  bailey:           {t:"3"},
  northarmrice:     {t:"3"},
  hotsprings:       {t:"3"},
  summitcreeklavo:  {t:"3"},
  mercedriver:      {t:"gold"},
  sfmerced:         {t:"1"},
  tuolumneriver:    {t:"gold"},
  lyellfork:        {t:"1"},
  danafork:         {t:"2"},
  lyellforkmerced:  {t:"3"},
  sftuolumne:       {t:"3"},
  tenaya:           {t:"2"},
  yosemitecreek:    {t:"3"},
  bridalveil:       {t:"3"},
  illilouette:      {t:"3"},
  cathedral:        {t:"3"},
  returncreek:      {t:"3"},
  rancheria:        {t:"3"},
  fallscreekyose:   {t:"3"},
  mftuolumne:       {t:"2"},
  sfkings:          {t:"gold"},
  mfkings:          {t:"1"},
  bubbs:            {t:"2"},
  roaring:          {t:"2"},
  evolution:        {t:"2"},
  woods:            {t:"3"},
  copper:           {t:"3"},
  goddard:          {t:"3"},
  dusy:             {t:"3"},
  kernriver:        {t:"gold"},
  mfkaweah:         {t:"1"},
  marblefork:       {t:"2"},
  efkaweah:         {t:"2"},
  sfkaweah:         {t:"2"},
  kernkaweah:       {t:"2"},
  bigarroyo:        {t:"2"},
  nfkaweah:         {t:"3"},
  rockcreekseki:    {t:"3"},
  sodacreek:        {t:"3"},
  whitney:          {t:"3"},
  wallace:          {t:"3"},
/* <<< western national parks */
/* >>> western state rivers (generated by states/apply.py — re-run, don't hand-edit) */
  /* ---- Montana, California, Oregon, Washington — drafts relative to each state ---- */
  madisonmt:       {t:"gold"},
  gallatinmt:      {t:"1"},
  jeffersonmt:     {t:"2"},
  bighole:         {t:"gold"},
  beaverhead:      {t:"gold"},
  rubymt:          {t:"1"},
  redrock:         {t:"2"},
  missourimt:      {t:"gold"},
  yellowstonemt:   {t:"gold"},
  bighornmt:       {t:"gold"},
  kootenaimt:      {t:"gold"},
  blackfootmt:     {t:"gold"},
  clarkforkmt:     {t:"1"},
  rockcreekmt:     {t:"gold"},
  bitterroot:      {t:"gold"},
  wfbitterroot:    {t:"2"},
  efbitterroot:    {t:"2"},
  nfblackfoot:     {t:"2", season:{closed:[[12,4]], why:"Western District streams open the third Saturday in May through Nov. 30, unless this river's own rules say otherwise."}},
  clearwatermt:    {t:"3"},
  littleblackfoot: {t:"2"},
  flintcreek:      {t:"3"},
  smithmt:         {t:"1"},
  dearborn:        {t:"2"},
  sunmt:           {t:"2"},
  boulderbt:       {t:"1"},
  stillwatermt:    {t:"1"},
  shields:         {t:"2"},
  bigspring:       {t:"1"},
  beltcreek:       {t:"3"},
  flatheadmt:      {t:"2"},
  sfflatheadmt:    {t:"1"},
  swanmt:          {t:"2"},
  yaak:            {t:"2", season:{closed:[[12,4]], why:"Western District streams open the third Saturday in May through Nov. 30, unless this river's own rules say otherwise."}},
  thompsonmt:      {t:"3"},
  fishermt:        {t:"3", season:{closed:[[12,4]], why:"Western District streams open the third Saturday in May through Nov. 30, unless this river's own rules say otherwise."}},
  rockcreekrl:     {t:"3"},
  wiseriver:       {t:"3"},
  poindexter:      {t:"2"},
  uppersac:        {t:"gold"},
  lowersac:        {t:"gold"},
  mccloud:         {t:"gold"},
  pitca:           {t:"1"},
  hatcreekca:      {t:"gold"},
  fallriverca:     {t:"gold"},
  burney:          {t:"3"},
  trinityca:       {t:"gold"},
  klamathca:       {t:"1"},
  smithca:         {t:"1"},
  eelca:           {t:"2"},
  sfeel:           {t:"2"},
  madca:           {t:"3"},
  scott:           {t:"2"},
  salmonca:        {t:"2"},
  mffeather:       {t:"1", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  nffeather:       {t:"2"},
  lowerfeather:    {t:"2"},
  nyuba:           {t:"2"},
  loweryuba:       {t:"1"},
  nfamerican:      {t:"2"},
  mfamerican:      {t:"2"},
  loweramerican:   {t:"1"},
  truckeeca:       {t:"1"},
  littletruckee:   {t:"1"},
  ecarson:         {t:"1"},
  wwalker:         {t:"2", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  ewalker:         {t:"gold"},
  upperowens:      {t:"gold"},
  lowerowens:      {t:"1"},
  hotcreek:        {t:"1"},
  rushcreek:       {t:"2"},
  bishopcreek:     {t:"2", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  rockcreekca:     {t:"3", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  kernca:          {t:"1"},
  sfkern:          {t:"1"},
  goldentrout:     {t:"1"},
  kingsca:         {t:"2"},
  mercedca:        {t:"2", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  mfstanislaus:    {t:"2"},
  nfmokelumne:     {t:"2", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  mfsanjoaquin:    {t:"2", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  putah:           {t:"1"},
  efsangabriel:    {t:"3", season:{poor:[[12,3]], why:"Under California's statewide stream rule, Nov 16 to late April is zero-bag, artificial barbless lures only."}},
  russianca:       {t:"2"},
  deepcreekca:     {t:"3"},
  lowerdeschutes:  {t:"gold"},
  middeschutes:    {t:"2"},
  updeschutes:     {t:"1"},
  metolius:        {t:"gold"},
  crookedor:       {t:"gold"},
  fallriveror:     {t:"1"},
  mckenzie:        {t:"gold"},
  nsantiam:        {t:"1"},
  ssantiam:        {t:"2"},
  mfwillamette:    {t:"1"},
  numpqua:         {t:"gold"},
  sumpqua:         {t:"3"},
  upperrogue:      {t:"gold"},
  lowerrogue:      {t:"1"},
  williamson:      {t:"gold"},
  woodriveror:     {t:"1"},
  sprague:         {t:"2"},
  klamathor:       {t:"1"},
  owyhee:          {t:"gold"},
  malheur:         {t:"3"},
  johnday:         {t:"2"},
  nfjohnday:       {t:"1"},
  granderondeor:   {t:"1"},
  imnaha:          {t:"2"},
  wallowa:         {t:"1"},
  minam:           {t:"2", season:{closed:[[11,4]], why:"Oregon streams in this zone open May 22 – Oct 31, unless this river's own exceptions say otherwise."}},
  wenaha:          {t:"2"},
  umatilla:        {t:"3"},
  hoodriver:       {t:"1"},
  clackamas:       {t:"1"},
  sandyor:         {t:"1"},
  wilsonor:        {t:"2"},
  trask:           {t:"2"},
  nestucca:        {t:"2"},
  siletz:          {t:"2"},
  alsea:           {t:"2"},
  chetco:          {t:"2"},
  elkor:           {t:"2"},
  illinoisor:      {t:"2"},
  powderor:        {t:"2"},
  donnerblitzen:   {t:"1"},
  yakimawa:        {t:"gold"},
  naches:          {t:"1"},
  tieton:          {t:"2", season:{closed:[[11,4]], why:"Washington rivers open the Saturday before Memorial Day through Oct 31, unless this river's Special Rules say otherwise."}},
  cleelum:         {t:"2"},
  teanaway:        {t:"3", season:{closed:[[11,4]], why:"Washington rivers open the Saturday before Memorial Day through Oct 31, unless this river's Special Rules say otherwise."}},
  methow:          {t:"gold"},
  twisp:           {t:"2", season:{closed:[[11,4]], why:"Washington rivers open the Saturday before Memorial Day through Oct 31, unless this river's Special Rules say otherwise."}},
  chewuch:         {t:"2"},
  wenatchee:       {t:"1"},
  icicle:          {t:"2", season:{closed:[[11,4]], why:"Washington rivers open the Saturday before Memorial Day through Oct 31, unless this river's Special Rules say otherwise."}},
  chiwawa:         {t:"2", season:{closed:[[11,4]], why:"Washington rivers open the Saturday before Memorial Day through Oct 31, unless this river's Special Rules say otherwise."}},
  entiat:          {t:"2"},
  skagitwa:        {t:"gold"},
  sauk:            {t:"1"},
  suiattle:        {t:"2", season:{closed:[[11,4]], why:"Washington rivers open the Saturday before Memorial Day through Oct 31, unless this river's Special Rules say otherwise."}},
  skykomish:       {t:"1"},
  mfsnoqualmie:    {t:"2"},
  nfstillaguamish: {t:"1"},
  nfnooksack:      {t:"2"},
  greenwa:         {t:"2"},
  cowlitzwa:       {t:"1"},
  kalama:          {t:"1"},
  nflewis:         {t:"1"},
  eflewis:         {t:"2"},
  washougal:       {t:"2"},
  windwa:          {t:"1"},
  klickitat:       {t:"gold"},
  whitesalmon:     {t:"2"},
  granderondewa:   {t:"gold"},
  tucannon:        {t:"2"},
  touchet:         {t:"3"},
  spokane:         {t:"1"},
  littlespokane:   {t:"2"},
  kettle:          {t:"2"},
  sanpoil:         {t:"2"},
  rockyford:       {t:"gold"},
  hohwa:           {t:"1"},
  solducwa:        {t:"1"},
  bogachielwa:     {t:"1"},
  calawah:         {t:"1"},
  quillayute:      {t:"2"},
  humptulips:      {t:"1"},
  wynoochee:       {t:"2"},
  satsop:          {t:"2"},
  dungeness:       {t:"2"},
  hoko:            {t:"2"},
  snakewa:         {t:"3"},
  hanfordreach:    {t:"2", season:{closed:[[11,4]], why:"Washington rivers open the Saturday before Memorial Day through Oct 31, unless this river's Special Rules say otherwise."}},
/* <<< western state rivers */
/* >>> michigan trout streams (generated by east/mi_apply.py — re-run, don't hand-edit) */
  /* ---- Michigan trout streams — drafts ---- */
  ausable:         {t:"gold"},
  nbausable:       {t:"1"},
  sbausable:       {t:"1"},
  manistee:        {t:"gold"},
  peremarquette:   {t:"gold"},
  littlemanistee:  {t:"1"},
  pinemi:          {t:"1", season:{closed:[[10,4]], why:"Type 1 and 2 trout streams are open the last Saturday in April through Sep. 30."}},
  muskegon:        {t:"1"},
  rifle:           {t:"2"},
  boardman:        {t:"2"},
  plattemi:        {t:"2"},
  jordan:          {t:"1"},
  pigeonmi:        {t:"2"},
  sturgeonmi:      {t:"1"},
  blackmi:         {t:"2"},
  betsie:          {t:"2"},
  whitemi:         {t:"2"},
  baldwin:         {t:"2", season:{closed:[[10,4]], why:"Type 1 and 2 trout streams are open the last Saturday in April through Sep. 30."}},
  twohearted:      {t:"gold"},
  foxmi:           {t:"1"},
  escanaba:        {t:"2"},
  yellowdog:       {t:"2", season:{closed:[[10,4]], why:"Type 1 and 2 trout streams are open the last Saturday in April through Sep. 30."}},
  salmontrout:     {t:"2"},
/* <<< michigan trout streams */
/* >>> wisconsin trout streams (generated by wi/apply.py — re-run, don't hand-edit) */
  /* ---- Wisconsin South Shore & central sands — drafts ---- */
  badriverwi:      {t:"2", season:{closed:[[12,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  whiteriverbay:   {t:"1", season:{closed:[[12,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  marengo:         {t:"1", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  siouxriver:      {t:"1"},
  cranberrywi:     {t:"2", season:{closed:[[12,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  siskiwit:        {t:"2"},
  flagriver:       {t:"2"},
  fishcreekwi:     {t:"2"},
  ironriverwi:     {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  brunsweiler:     {t:"2", season:{closed:[[12,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  tylerforks:      {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  mecan:           {t:"1", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  tomorrow:        {t:"1", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  littleplover:    {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  whiteriverwau:   {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  pineriverwau:    {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  willowwau:       {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  lawrencecr:      {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  chaffee:         {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  emmons:          {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  crystalwau:      {t:"2", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
  wedde:           {t:"3", season:{closed:[[11,12]], why:"Closed on every reach of this stream these months under WDNR regulations."}},
/* <<< wisconsin trout streams */
/* >>> rockies & alaska rivers (generated by rockies/apply.py — re-run, don't hand-edit) */
  /* ---- Colorado, Utah, Alaska and their parks — drafts relative to each state or park ---- */
  bigthompsonromo:   {t:"gold"},
  nfbigthompson:     {t:"2"},
  fallriverromo:     {t:"1"},
  coloradoromo:      {t:"1"},
  roaringromo:       {t:"2"},
  glaciercreekromo:  {t:"2"},
  poudreromo:        {t:"2"},
  sfpoudreromo:      {t:"3"},
  nstvrainromo:      {t:"2"},
  onahu:             {t:"2"},
  tonahutu:          {t:"2"},
  northinlet:        {t:"2"},
  eastinlet:         {t:"2"},
  timbercreekromo:   {t:"3"},
  haguecreek:        {t:"3"},
  ouzelcreek:        {t:"3"},
  conycreek:         {t:"3"},
  hunterscreek:      {t:"3"},
  sandbeachcreek:    {t:"3"},
  columbinecreekromo: {t:"3"},
  westcreekromo:     {t:"3"},
  gunnisonblca:      {t:"gold"},
  medanocreek:       {t:"2"},
  sandcreekgrsa:     {t:"3"},
  southplatte:       {t:"gold"},
  mfsouthplatte:     {t:"2"},
  sfsouthplatte:     {t:"2"},
  arkansasco:        {t:"gold"},
  lakeforkark:       {t:"3"},
  blueriverco:       {t:"gold"},
  coloradoco:        {t:"gold"},
  fraser:            {t:"1"},
  williamsfork:      {t:"2"},
  eagleriverco:      {t:"1"},
  gorecreek:         {t:"2"},
  roaringforkco:     {t:"gold"},
  fryingpan:         {t:"gold"},
  crystalco:         {t:"2"},
  taylorriver:       {t:"gold"},
  eastriverco:       {t:"2"},
  gunnisonupper:     {t:"gold"},
  gunnisongorge:     {t:"gold"},
  lakeforkgunnison:  {t:"1"},
  cimarron:          {t:"2"},
  uncompahgre:       {t:"2"},
  sanmiguel:         {t:"1"},
  doloresco:         {t:"1"},
  animas:            {t:"1"},
  lospinos:          {t:"2"},
  piedra:            {t:"2"},
  sanjuanco:         {t:"2"},
  riograndeco:       {t:"gold"},
  sfriogrande:       {t:"2"},
  conejos:           {t:"1"},
  yampaco:           {t:"1"},
  elkriverco:        {t:"2"},
  whiteriverco:      {t:"1"},
  northplatteco:     {t:"1"},
  michigan:          {t:"2"},
  poudre:            {t:"1"},
  bigthompsonco:     {t:"1"},
  stvrain:           {t:"2"},
  southboulder:      {t:"2"},
  clearcreekco:      {t:"3"},
  tarryall:          {t:"2"},
  cochetopa:         {t:"3"},
  saguache:          {t:"2"},
  brooksriver:       {t:"gold"},
  americancreek:     {t:"1"},
  morainecreek:      {t:"gold"},
  funnelcreek:       {t:"1"},
  nonvianuk:         {t:"1"},
  margotcreek:       {t:"2"},
  savonoski:         {t:"3"},
  ukak:              {t:"3"},
  chilikadrotna:     {t:"1"},
  mulchatnalacl:     {t:"2"},
  kijik:             {t:"2"},
  tazimina:          {t:"2"},
  chulitnalacl:      {t:"2"},
  tlikakila:         {t:"3"},
  telaquana:         {t:"3"},
  crescentlacl:      {t:"2"},
  moosecreekdena:    {t:"2"},
  rileycreek:        {t:"3"},
  savagedena:        {t:"3"},
  sanctuary:         {t:"3"},
  teklanika:         {t:"3"},
  toklat:            {t:"3"},
  tokositna:         {t:"3"},
  bullriverdena:     {t:"3"},
  copperwrst:        {t:"3"},
  chitina:           {t:"3"},
  nabesna:           {t:"3"},
  tanadacreek:       {t:"2"},
  jackcreekwrst:     {t:"2"},
  tebay:             {t:"2"},
  kennicott:         {t:"3"},
  chisana:           {t:"3"},
  bremner:           {t:"3"},
  kobukgaar:         {t:"1"},
  noatakgaar:        {t:"1"},
  alatna:            {t:"2"},
  johnriver:         {t:"2"},
  nfkoyukuk:         {t:"2"},
  killik:            {t:"3"},
  reedriver:         {t:"3"},
  kobukkova:         {t:"1"},
  salmonkova:        {t:"2"},
  kallarichuk:       {t:"3"},
  tutuksuk:          {t:"3"},
  bartlett:          {t:"1"},
  dundas:            {t:"2"},
  alsek:             {t:"3"},
  doame:             {t:"3"},
  eastalsek:         {t:"2"},
  nuka:              {t:"3"},
  kenai:             {t:"gold"},
  russian:           {t:"gold"},
  kasilof:           {t:"1"},
  anchorriver:       {t:"1"},
  deepcreekak:       {t:"2"},
  ninilchik:         {t:"2"},
  quartzcreekak:     {t:"2"},
  swanson:           {t:"2"},
  deshka:            {t:"1"},
  littlesusitna:     {t:"1"},
  willowcreekak:     {t:"1"},
  montanacreekak:    {t:"2"},
  sheepcreekak:      {t:"2"},
  lakecreekak:       {t:"1"},
  talachulitna:      {t:"1"},
  alexandercreek:    {t:"2"},
  talkeetna:         {t:"2"},
  chunilna:          {t:"2"},
  shipcreek:         {t:"3"},
  gulkana:           {t:"gold"},
  mfgulkana:         {t:"1"},
  klutina:           {t:"1"},
  tonsina:           {t:"2"},
  chena:             {t:"1"},
  deltaclearwater:   {t:"1"},
  goodpaster:        {t:"2"},
  salcha:            {t:"2"},
  chatanika:         {t:"2"},
  naknek:            {t:"gold"},
  alagnak:           {t:"gold"},
  kvichak:           {t:"gold"},
  newhalen:          {t:"1"},
  copperiliamna:     {t:"gold"},
  gibraltar:         {t:"1"},
  uppertalarik:      {t:"2"},
  iliamnariver:      {t:"2"},
  nushagak:          {t:"1"},
  mulchatna:         {t:"2"},
  koktuli:           {t:"1"},
  agulukpak:         {t:"1"},
  nuyakuk:           {t:"2"},
  togiak:            {t:"1"},
  kanektok:          {t:"gold"},
  goodnews:          {t:"1"},
  arolik:            {t:"2"},
  karluk:            {t:"gold"},
  ayakulik:          {t:"1"},
  buskin:            {t:"1"},
  uganik:            {t:"2"},
  situk:             {t:"gold"},
  italio:            {t:"2"},
  chilkat:           {t:"2"},
  chilkoot:          {t:"2"},
  montanacreekjnu:   {t:"2"},
  petersoncreekjnu:  {t:"2"},
  cowee:             {t:"2"},
  petersburgcreek:   {t:"2"},
  anancreek:         {t:"3"},
  thorne:            {t:"1"},
  karta:             {t:"1"},
  klawock:           {t:"2"},
  staney:            {t:"2"},
  naha:              {t:"2"},
  aniak:             {t:"1"},
  kisaralik:         {t:"1"},
  kwethluk:          {t:"2"},
  unalakleet:        {t:"1"},
  ugashik:           {t:"2"},
  eagleriverak:      {t:"3"},
  campbellcreek:     {t:"3"},
  birdcreek:         {t:"3"},
  ptarmigancreek:    {t:"3"},
  coopercreekak:     {t:"3"},
  stariski:          {t:"3"},
  mooseriverak:      {t:"2"},
  funnyriver:        {t:"3"},
  lowertalarik:      {t:"1"},
  stuyahok:          {t:"2"},
  kadashan:          {t:"2"},
  kellycreek:        {t:"gold"},
  owyheeid:          {t:"3"},
  greybull:          {t:"2"},
  hamsfork:          {t:"2"},
  rapidcreek:        {t:"gold"},
  spearfish:         {t:"1"},
  castlecreek:       {t:"2"},
  frenchcreeksd:     {t:"3"},
  springcreeksd:     {t:"2"},
  whitewood:         {t:"3"},
  sanjuannm:         {t:"gold"},
  riochama:          {t:"1"},
  riograndenm:       {t:"1"},
  pecos:             {t:"1"},
  rioguadalupe:      {t:"2"},
  jemez:             {t:"2"},
  costilla:          {t:"2"},
  cimarronnm:        {t:"1"},
  redrivernm:        {t:"2"},
  gilanm:            {t:"2"},
  whitewatercreek:   {t:"2"},
  coloradograca:     {t:"2"},
  brightangel:       {t:"2"},
  leesferry:         {t:"gold"},
  oakcreek:          {t:"1"},
  silvercreekaz:     {t:"2"},
  littlecolorado:    {t:"2"},
  blackriveraz:      {t:"2"},
  canyoncreekaz:     {t:"2"},
  westclear:         {t:"2"},
  lehmancreek:       {t:"2"},
  bakercreeknv:      {t:"3"},
  snakecreeknv:      {t:"2"},
  truckeenv:         {t:"1"},
  eastwalkernv:      {t:"1"},
  lamoille:          {t:"3"},
  jarbidge:          {t:"2"},
  marysriver:        {t:"3"},
  fremontcare:       {t:"2"},
  sulphurcreekcare:  {t:"3"},
  pleasantcreekcare: {t:"3"},
  nfvirgin:          {t:"3"},
  efvirginzion:      {t:"3"},
  laverkin:          {t:"3"},
  northcreekzion:    {t:"3"},
  greencany:         {t:"3"},
  coloradocany:      {t:"3"},
  greenut:           {t:"gold"},
  provo:             {t:"gold"},
  weberut:           {t:"1"},
  logan:             {t:"1"},
  blacksmithfork:    {t:"2"},
  ogden:             {t:"2"},
  sfogden:           {t:"2"},
  strawberryriver:   {t:"1"},
  duchesne:          {t:"2"},
  currantcreek:      {t:"2"},
  huntingtoncreek:   {t:"2"},
  fremontut:         {t:"2"},
  efsevier:          {t:"2"},
  beaverriverut:     {t:"2"},
  bearriverut:       {t:"2"},
  littlebear:        {t:"2"},
  uintariver:        {t:"2"},
  whiterocks:        {t:"2"},
  rockcreekut:       {t:"2"},
  lakeforkut:        {t:"2"},
  ashleycreek:       {t:"2"},
  sheepcreekut:      {t:"3", season:{closed:[[9,11]], why:"Closed Aug. 15 through 6 a.m. on the last Saturday of November."}},
  americanfork:      {t:"3"},
  spanishfork:       {t:"3"},
  diamondfork:       {t:"2"},
  escalante:         {t:"3"},
  blacksforkut:      {t:"2"},
  chalkcreek:        {t:"3"},
  panguitch:         {t:"2"},
  bigcottonwood:     {t:"3"},
  eastcanyon:        {t:"2"},
  priceriver:        {t:"3"},
  wfduchesne:        {t:"2"},
  mammothcreek:      {t:"2"},
/* <<< rockies & alaska rivers */
/* >>> western rulebook streams (generated by west2/apply.py — re-run, don't hand-edit) */
  /* ---- Montana & Colorado rulebook streams (every water with its own entry in the state's exceptions) — drafts relative to the state ---- */
  alicecreekmt2:                     {t:"2"},
  bearcreekmiddleforkflatheadrivermt2: {t:"2"},
  belmontcreekmt2:                   {t:"2"},
  bigcreekmt2:                       {t:"2"},
  bigsalmoncreekmt2:                 {t:"2"},
  chamberlaincreekmt2:               {t:"2"},
  coalcreeknorthforkflatheadrivermt2: {t:"2"},
  dalycreekmt2:                      {t:"2"},
  drycreekclarkforkrivermt2:         {t:"2"},
  dunhamcreekmt2:                    {t:"2"},
  elkcreekswanrivermt2:              {t:"2"},
  fishcreekclarkforkrivermt2:        {t:"2"},
  fishtrapcreekmt2:                  {t:"2"},
  goatcreekmt2:                      {t:"2"},
  goldcreekmt2:                      {t:"2"},
  granitecreekmiddleforkflatheadrivermt2: {t:"2"},
  gravecreekmt2:                     {t:"2"},
  herrigcreekmt2:                    {t:"2"},
  hollandcreekmt2:                   {t:"2"},
  keelercreekmt2:                    {t:"2"},
  lakecreektroymt2:                  {t:"2"},
  landersforkmt2:                    {t:"2"},
  lioncreekmt2:                      {t:"2"},
  lodgepolecreekmt2:                 {t:"2"},
  longcreekmt2:                      {t:"2"},
  marshallcreekmt2:                  {t:"2"},
  millcreekclarkforkrivermt2:        {t:"2"},
  monturecreekmt2:                   {t:"2"},
  morrellcreekmt2:                   {t:"2"},
  morrisoncreekmt2:                  {t:"2"},
  nevadacreekmt2:                    {t:"2"},
  northforkflintcreekmt2:            {t:"2"},
  pettycreekmt2:                     {t:"2"},
  placidcreekmt2:                    {t:"2"},
  quartzcreekkootenairivermt2:       {t:"2"},
  rattlesnakecreekmissoulamt2:       {t:"2"},
  silverbowcreekmt2:                 {t:"2"},
  skalkahocreekmt2:                  {t:"2"},
  snowbankcreekmt2:                  {t:"2"},
  squeezercreekmt2:                  {t:"2"},
  stregisrivermt2:                   {t:"2"},
  stillwaterriverflatheadrivermt2:   {t:"2"},
  stormlakecreekmt2:                 {t:"2"},
  tobaccorivermt2:                   {t:"2"},
  trailcreeknorthforkflatheadrivermt2: {t:"2"},
  troutcreekclarkforkrivermt2:       {t:"2"},
  warmspringscreekanacondamt2:       {t:"2"},
  westforkclearwaterrivermt2:        {t:"2"},
  westforkthompsonrivermt2:          {t:"2"},
  whalecreekmt2:                     {t:"2"},
  whitefishrivermt2:                 {t:"2"},
  woodwardcreekmt2:                  {t:"2"},
  badgercreekheartbuttemt2:          {t:"2"},
  beavercreekcanyonferryreservoirmt2: {t:"2"},
  beavercreekmissouririvermt2:       {t:"2"},
  blacktaildeercreekbeaverheadrivermt2: {t:"2"},
  boulderriverjeffersonrivermt2:     {t:"2"},
  clarksforkyellowstonerivermt2:     {t:"2"},
  cottonwoodcreekmartinsdalemt2:     {t:"2"},
  cutbankcreekoutsideglaciermt2:     {t:"2"},
  deepcreekmissouririvermt2:         {t:"2"},
  drycreekmissouririvermt2:          {t:"2"},
  duckcreekhebgenreservoirmt2:       {t:"2"},
  eastforkhyalitecreekmt2:           {t:"2"},
  eastgallatinrivermt2:              {t:"2"},
  graylingcreekhebgenreservoirmt2:   {t:"2"},
  haymakercreekmt2:                  {t:"2"},
  hellroaringcreekyellowstonerivermt2: {t:"2"},
  hellscanyoncreekmt2:               {t:"2"},
  hyalitecreekmt2:                   {t:"2"},
  littlepricklypearcreekmt2:         {t:"2"},
  lymancreekmt2:                     {t:"2"},
  magpiecreekcanyonferryreservoirmt2: {t:"2"},
  midvalecreekmt2:                   {t:"2"},
  northforksunrivermt2:              {t:"2"},
  northwillowcreekmt2:               {t:"2"},
  norwegiancreekmt2:                 {t:"2"},
  obriencreekmt2:                    {t:"2"},
  parsonssloughmt2:                  {t:"2"},
  rattlesnakecreekdillonmt2:         {t:"2"},
  sheepcreekmissouririvermt2:        {t:"2"},
  sloughcreekyellowstonerivermt2:    {t:"2"},
  sodabuttecreekyellowstonerivermt2: {t:"2"},
  southforkmadisonrivermt2:          {t:"2"},
  southforksunrivermt2:              {t:"2"},
  southforktwomedicinerivermt2:      {t:"2"},
  southwillowcreekmt2:               {t:"2"},
  troutcreekmissouririvermt2:        {t:"2"},
  willowcreekwhitesulphurspringsmt2: {t:"2"},
  judithrivermt2:                    {t:"2"},
  mariasrivermt2:                    {t:"2"},
  musselshellrivermt2:               {t:"2"},
  tonguerivermontanamt2:             {t:"2"},
  abramscreekco2:                    {t:"2"},
  westantelopecreekco2:              {t:"2"},
  northforkanthracitecreekco2:       {t:"2"},
  arapahocreekco2:                   {t:"2"},
  archuletacreekco2:                 {t:"2"},
  middleforksoutharkansasriverco2:   {t:"2"},
  augustoracreekco2:                 {t:"2"},
  bardcreekco2:                      {t:"2"},
  basincreekgunnisonco2:             {t:"2"},
  bearcreekconejosco2:               {t:"2"},
  bearcreekelpasoco2:                {t:"2"},
  bearcreekjeffersonco2:             {t:"2"},
  bearcreekmontezumaco2:             {t:"2"},
  beavercreekgarfieldco2:            {t:"2"},
  beavercreekmineralco2:             {t:"2"},
  westbeavercreekco2:                {t:"2"},
  beaverdamscreekco2:                {t:"2"},
  bigbendcreekco2:                   {t:"2"},
  bigholecreekco2:                   {t:"2"},
  bobtailcreekco2:                   {t:"2"},
  bouldercreekboulderco2:            {t:"2"},
  brushcreekeagleco2:                {t:"2"},
  westbrushcreekco2:                 {t:"2"},
  cabincreekgarfieldco2:             {t:"2"},
  canyoncreekgarfieldco2:            {t:"2"},
  middlecarnerocreekco2:             {t:"2"},
  northcarnerocreekco2:              {t:"2"},
  southcarnerocreekco2:              {t:"2"},
  cartercreekco2:                    {t:"2"},
  cascadecreekconejosco2:            {t:"2"},
  cascadecreekhuerfanoco2:           {t:"2"},
  castlecreeklaplataco2:             {t:"2"},
  catcreekco2:                       {t:"2"},
  northforkcatcreekco2:              {t:"2"},
  southforkcatcreekco2:              {t:"2"},
  cataractcreekco2:                  {t:"2"},
  chaircreekco2:                     {t:"2"},
  chalkcreekchaffeeco2:              {t:"2"},
  northcheyennecreekco2:             {t:"2"},
  clearcreekchaffeeco2:              {t:"2"},
  clearcreeklaplataco2:              {t:"2"},
  westforkclearcreekco2:             {t:"2"},
  clearforkofmuddycreekco2:          {t:"2"},
  cliffcreekgunnisonco2:             {t:"2"},
  corneliuscreekco2:                 {t:"2"},
  corralcreeksanjuanco2:             {t:"2"},
  corralcreeksummitco2:              {t:"2"},
  littlecottonwoodcreekmoffatco2:    {t:"2"},
  culebracreekco2:                   {t:"2"},
  cunninghamcreekdeltaco2:           {t:"2"},
  cunninghamcreekpitkinco2:          {t:"2"},
  deepcreeklaplataco2:               {t:"2"},
  deepcreeksanmiguelco2:             {t:"2"},
  deerbeavercreekco2:                {t:"2"},
  disappointmentcreekco2:            {t:"2"},
  dougcreekco2:                      {t:"2"},
  duckcreekclearcreekco2:            {t:"2"},
  eastpasscreekco2:                  {t:"2"},
  elkcreekgarfieldco2:               {t:"2"},
  elkcreeksanmiguelco2:              {t:"2"},
  northforkescalantecreekco2:        {t:"2"},
  fallcreekmineralco2:               {t:"2"},
  fallcreeksanmiguelco2:             {t:"2"},
  fawncreekrioblancoco2:             {t:"2"},
  fishcreekrouttco2:                 {t:"2"},
  floridariverco2:                   {t:"2"},
  fourmilecreekco2:                  {t:"2"},
  frasercreekco2:                    {t:"2"},
  frenchgulchco2:                    {t:"2"},
  georgecreekco2:                    {t:"2"},
  goatcreeksanmiguelco2:             {t:"2"},
  grassycreekco2:                    {t:"2"},
  greenrivermoffatco2:               {t:"2"},
  grimescreekco2:                    {t:"2"},
  grizzlycreekco2:                   {t:"2"},
  groundhogcreekco2:                 {t:"2"},
  northforkgunnisonriverco2:         {t:"2"},
  hahncreekco2:                      {t:"2"},
  hamiltoncreekco2:                  {t:"2"},
  hatcreekeagleco2:                  {t:"2"},
  headachecreekco2:                  {t:"2"},
  hermangulchco2:                    {t:"2"},
  hermosacreekco2:                   {t:"2"},
  eastforkhermosacreekco2:           {t:"2"},
  himescreekco2:                     {t:"2"},
  mainhubbardcreekco2:               {t:"2"},
  middlehubbardcreekco2:             {t:"2"},
  huerfanoriverco2:                  {t:"2"},
  illinoisriverjacksonco2:           {t:"2"},
  jimcreekco2:                       {t:"2"},
  joewrightcreekco2:                 {t:"2"},
  kaufmancreekco2:                   {t:"2"},
  kelsocreekco2:                     {t:"2"},
  laplatariverco2:                   {t:"2"},
  laramieriverlarimerco2:            {t:"2"},
  lestercreekco2:                    {t:"2"},
  lonepinecreekco2:                  {t:"2"},
  lospinoscreekco2:                  {t:"2"},
  losttrailcreekco2:                 {t:"2"},
  mancosriverco2:                    {t:"2"},
  maycreekco2:                       {t:"2"},
  mcelmocreekco2:                    {t:"2"},
  meadowcreekeagleco2:               {t:"2"},
  eastmeadowcreekco2:                {t:"2"},
  eastmiddlecreekco2:                {t:"2"},
  southforkminnesotacreekco2:        {t:"2"},
  mitchellcreekco2:                  {t:"2"},
  natecreekco2:                      {t:"2"},
  navajoriverco2:                    {t:"2"},
  newlincreekco2:                    {t:"2"},
  nickelsoncreekco2:                 {t:"2"},
  nolancreekco2:                     {t:"2"},
  northforknorthplatteriverco2:      {t:"2"},
  northtaylorcreekco2:               {t:"2"},
  northwatercreekco2:                {t:"2"},
  osiercreekco2:                     {t:"2"},
  eastforkparachutecreekco2:         {t:"2"},
  eastmiddleforkparachutecreekco2:   {t:"2"},
  passcreekco2:                      {t:"2"},
  pasturecreekco2:                   {t:"2"},
  pettycreeksanjuanco2:              {t:"2"},
  eastforkpiedrariverco2:            {t:"2"},
  pointscreekco2:                    {t:"2"},
  poosecreekco2:                     {t:"2"},
  northforkpoudreriverco2:           {t:"2"},
  southforkpoudreriverco2:           {t:"2"},
  pryorcreekco2:                     {t:"2"},
  middleforkpurgatoireriverco2:      {t:"2"},
  southforkpurgatoireriverco2:       {t:"2"},
  northforkranchcreekco2:            {t:"2"},
  relaycreekco2:                     {t:"2"},
  ritohondocreekco2:                 {t:"2"},
  roadbeavercreekco2:                {t:"2"},
  roaringcreekco2:                   {t:"2"},
  roaringforkofthenorthplatteco2:    {t:"2"},
  roaringforkmineralco2:             {t:"2"},
  roaringforkscreekco2:              {t:"2"},
  robinsoncreekgunnisonco2:          {t:"2"},
  rockcreeklakeco2:                  {t:"2"},
  rockcreekparkco2:                  {t:"2"},
  littlerockcreekco2:                {t:"2"},
  middleforksaguachecreekco2:        {t:"2"},
  southforksaguachecreekco2:         {t:"2"},
  schwachheimcreekco2:               {t:"2"},
  secondcreekdeltaco2:               {t:"2"},
  severycreekco2:                    {t:"2"},
  sheepcreekconejosco2:              {t:"2"},
  eastforksheepcreekco2:             {t:"2"},
  westforksheepcreekco2:             {t:"2"},
  sigcreekco2:                       {t:"2"},
  eastforksigcreekco2:               {t:"2"},
  slatecreekco2:                     {t:"2"},
  southforkslatercreekco2:           {t:"2"},
  snellcreekco2:                     {t:"2"},
  springcreekdoloresco2:             {t:"2"},
  steelmancreekco2:                  {t:"2"},
  westforksteubencreekco2:           {t:"2"},
  swanriversummitco2:                {t:"2"},
  northforkswanriverco2:             {t:"2"},
  littletaylorcreekco2:              {t:"2"},
  tenmilecreeksummitco2:             {t:"2"},
  eastforkterrorcreekco2:            {t:"2"},
  westforkterrorcreekco2:            {t:"2"},
  threelickscreekco2:                {t:"2"},
  threemilecreekco2:                 {t:"2"},
  torsidocreekco2:                   {t:"2"},
  trappercreekco2:                   {t:"2"},
  troutcreekrioblancoco2:            {t:"2"},
  tuttlecreekco2:                    {t:"2"},
  northtwincreekco2:                 {t:"2"},
  southtwincreekco2:                 {t:"2"},
  vallecitocreekco2:                 {t:"2"},
  littlevasquezcreekco2:             {t:"2"},
  westcreekmesaco2:                  {t:"2"},
  westcrosscreekco2:                 {t:"2"},
  northforkwhiteriverco2:            {t:"2"},
  southforkwhiteriverco2:            {t:"2"},
  wildcatcreekco2:                   {t:"2"},
  willowcreekmoffatco2:              {t:"2"},
  wolfcreekconejosco2:               {t:"2"},
  wolfcreekmineralco2:               {t:"2"},
/* <<< western rulebook streams */
/* >>> wyoming wgfd streams (generated by wy/apply.py — re-run, don't hand-edit) */
  /* ---- Wyoming Area 1 streams from WGFD's Fishing Guide: Yellow Ribbon → 2 (Blue → 1); Grand Teton water closes Dec–Jul ---- */
  wg_southbadgercreek:           {t:"2"},
  wg_barbcspringcreek:           {t:"2"},
  wg_bigspringspencer:           {t:"2"},
  wg_blacktailspringcreek:       {t:"2", season:{closed:[[12,7]], why:"Park streams open August 1."}},
  wg_bluecranecreek:             {t:"2"},
  wg_northbuffalofork:           {t:"2"},
  wg_southbuffalofork:           {t:"2"},
  wg_burtonspring:               {t:"2"},
  wg_christensenspring:          {t:"2"},
  wg_codycreek:                  {t:"2"},
  wg_collierspringscreek:        {t:"2"},
  wg_cowboycabincreek:           {t:"2", season:{closed:[[12,7]], why:"Park streams open August 1."}},
  wg_cranneycreek:               {t:"2"},
  wg_crescenthspring:            {t:"2"},
  wg_crowcreek:                  {t:"2"},
  wg_crystalcreek:               {t:"2"},
  wg_darbycreek:                 {t:"2"},
  wg_fishcreekwilson:            {t:"2"},
  wg_fishcreekgv:                {t:"2"},
  wg_southforkfishcreek:         {t:"2"},
  wg_flatcreekstarvalley:        {t:"2"},
  wg_foxcreek:                   {t:"2"},
  wg_nowlincreek:                {t:"2", season:{closed:[[11,7]], why:"Chapter 46 closes the lowest 1,000 yards above Flat Creek November 1 through July 31, and the creek above the “Closed Area” signs all year."}},
  wg_polecatcreek:               {t:"2"},
  wg_shoalcreek:                 {t:"2"},
  wg_northforkspreadcreek:       {t:"2"},
  wg_springcreekjackson:         {t:"2"},
  wg_squirrelcreek:              {t:"2"},
  wg_southforktetoncreek:        {t:"2"},
  wg_threechannelspringcreek:    {t:"2"},
  wg_trailcreek:                 {t:"2"},
/* <<< wyoming wgfd streams */
};

const TIER_INFO = {
  gold:{label:"Gold",    short:"Gold", color:"#c79a1c", blurb:"Destination water"},
  "1": {label:"Class 1", short:"1",    color:"#0e6f7d", blurb:"Very good"},
  "2": {label:"Class 2", short:"2",    color:"#5a8a8f", blurb:"Good"},
  "3": {label:"Class 3", short:"3",    color:"#8b9690", blurb:"The rest"},
};

const inWindow = (m, wins) => !!wins && wins.some(([a,b]) => a<=b ? (m>=a && m<=b) : (m>=a || m<=b));
const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const winText = wins => wins.map(([a,b]) => a===b ? MONTHS[a-1] : MONTHS[a-1]+"–"+MONTHS[b-1]).join(", ");

/* The class a river holds in a given month.
   Returns {tier, base, state, why}: `state` is "best" | "poor" | "closed" | null. */
function tierOf(r, date){
  const e = TIERS[r.id];
  const base = e ? e.t : "3";
  const m = (date || new Date()).getMonth() + 1;
  const s = e && e.season;
  if(!s) return {tier:base, base, state:null, why:""};
  if(inWindow(m, s.closed)) return {tier:"3", base, state:"closed", why:s.why||"", wins:s.closed};
  let i = TIER_ORDER.indexOf(base), state = null;
  if(inWindow(m, s.best)){ i = Math.min(3, i+1); state = "best"; }
  else if(inWindow(m, s.poor)){ i = Math.max(0, i-1); state = "poor"; }
  return {tier:TIER_ORDER[i], base, state, why:s.why||"", wins: state==="best"?s.best : state==="poor"?s.poor : null};
}
